### ISSUE TITLE
Problem with `readline` module when handing history navigation using up-arrow key

### ISSUE THREAD

**Issue by efJerryYang** [efJerryYang/chatgpt-cli#12]
Initially, I encountered an unknown problem with the `readline` module, which compelled me to remove its usage in #11. Unfortunately, this brought about a new problem - poor handling of inputs such as cursor movements using left and right arrow keys. Therefore, I had to revert back to the use of the `readline` module provided by the `pyreadline3` package, which is compatible with both Linux and Windows. 

I removed the usage in this commit 0f13332, which seemed to be a wrong decision.

I open this issue to track the problem with using the `readline` module. Although I cannot recall the exact details of the issue, I will monitor my daily usage for a week, and close this issue if no further problems arise.

**Comment by efJerryYang** [comment]
Problem 1: Non-ASCII characters display and backspace problem. If you enter non-ASCII characters (especially those occupying more than one unit of width) and try to clear the input using backspace, you will get an incomplete clearing on the terminal display but actually complete clearing to the line buffer, which can be very confusing when encountering this problem for the first time.

**Comment by efJerryYang** [comment]
Problem 1: Non-ASCII characters display and backspace problem. If you enter non-ASCII characters (especially those occupying more than one unit of width) and try to clear the input using backspace, you will get an incomplete clearing on the terminal display but actually complete clearing to the line buffer, which can be very confusing when encountering this problem for the first time.

**Comment by PraxTube** [comment]
It seems like the multi-line feature is still causing problems. I know that you are used to it by now, but I seriously think that a proper terminal editor is a much cleaner solution. Perhaps we could even allow for a command like `!e` to make it more accessible.

I think supporting both is also no problem, but if the implementation is causing even more problems I don't know if it's worth it.

**Comment by efJerryYang** [comment]
I thought as you have said, but the multi-line handling was actually not directly provided by `readline` module. You can have a look at the source code  (I also forgot some of the logic till I read it again yesterday) that it actually handles the line handling simply by appending submitted lines to a list: https://github.com/efJerryYang/chatgpt-cli/blob/19abe791a4acf38e15d28e516bcc4da47fb235d5/src/utils/io.py#L114-L124

The `readline` here is mainly for special key handling (e.g., arrow keys), and I tried removing it in commit https://github.com/efJerryYang/chatgpt-cli/commit/0f13332e83d69ec7348e3804ee88bba32d4c748b but caused a problem for processing the arrow keys (e.g., moving the cursor left or right to insert characters). The reason why I open this issue is just as I mentioned earlier in this thread, to track the potential problems caused by `readline`, but I forgot what the problem is precisely (and it works fine without problems so far).

Currently, if we simply remove it as I did in https://github.com/efJerryYang/chatgpt-cli/commit/0f13332e83d69ec7348e3804ee88bba32d4c748b, the prompt provide by the tool will not work properly because there is a feature provided by the Python built-in `input()` method, it will read actually what the input characters are and not interpret them as special keys, and we should provide other alternatives like you mentioned in #6 which may raise some time cost to refactoring. So I retain its usage at the moment.

Additionally, I think the suggestion of using the abbreviation `!e` here will be helpful. I will add it later.

**Comment by PraxTube** [comment]
I can see your point. Leaving it in as is is probably best.
