### ISSUE TITLE
Rate Limit Error

### ISSUE THREAD

**Issue by PraxTube** [efJerryYang/chatgpt-cli#19]
I am getting the following error whenever I send a prompt.

```
╭────────────────────────────── ChatGPT CLI ───────────────────────────────╮
│ [Rate Limit Error] This is caused by API outage. Please try again later. │
╰──────────────────────────────────────────────────────────────────────────╯
```

I created a new API key but the error persists. I first thought that I reached the maximum tokens you are allowed in the free version, but I can still use ChatGPT in the browser without any problems. Could it be that there are some problems with the API? Are you able to use the CLI tool without any problems?

**Comment by efJerryYang** [comment]
Yes I can use my API at the moment, but this problem may still be caused by the temporary API limit from the server side. If you want to make sure you have access to your API and it is not caused by the runout of the maximum free trial ($15 previously, $5 currently), you can check your API key profile at https://platform.openai.com/account/api-keys.

**Comment by efJerryYang** [comment]
Additionally, even if the free trial is out of date (or you have run out of the free $15 or $5 provided by OpenAI), you can still use the ChatGPT from the official web client. If you want to use API in the case that you have run out of all the free trial tokens, you need to pay for it (set up a paid account) or create a new account, rather than generate a new API key.

**Comment by efJerryYang** [comment]
I have just tried with an invalid API key, the error message would be like this:

```txt

You exceeded your current quota, please check your plan and billing details.

╭────────────────────────────────────────────────── ChatGPT CLI ───────────────────────────────────────────────────╮
│ [Rate Limit Error] This is caused by API outage. Please try again later.                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Do you want to retry now? (y/n):
```
You should be able to see this line: `You exceeded your current quota, please check your plan and billing details.`.

I hope this can help!

**Comment by PraxTube** [comment]
Ah I see, thank you. I didn't know that the web application still works even if you exceeded your price limit.

So it seems like the free trial for API usage [expired yesterday](https://community.openai.com/t/i-hope-to-extend-the-time-of-free-trial-usage/125866). Which is also [stated here](https://help.openai.com/en/articles/4936830-what-happens-after-i-use-my-free-tokens-or-the-3-months-is-up-in-the-free-trial).

**Comment by efJerryYang** [comment]
Yes, those who started the ChatGPT in early March would probably have an API expiration date of April 1st. I have mentioned possible solutions to it in my previous comment:

>  If you want to use API in the case that you have run out of all the free trial tokens, you need to pay for it (set up a paid account) or create a new account, rather than generate a new API key.

And other possible alternatives could be to use the LLaMA models (from 7B to 65B) and corresponding fine-tuned models (many of which are good enough to take the place of GPT3.5-based ChatGPT) provided by opensource communities (for 7B models, Alpaca and Vicuna are famous ones, and there are also many others), but you need GPUs (I remember it needs 4 A100 to do the fine-tuning :sob: ). Though the cost of just running the fine-tuned models would be much more acceptable, it is still unaffordable for me, and I have to continue using the API by OpenAI for many days.

**Comment by PraxTube** [comment]
Wow you know quite a lot about this (at least it seems that way to me, who knows rather little haha). Yes I also think using the payed version of ChatGPT is a much more convenient solution (both from the usage and the pricing). Even if you had that much computation power (I have one GPU with 2 VRAM :cry:), you would still need to pay the electricity to run all of those computations.
