### ISSUE TITLE
Cannot support windows due to the use of `readline` module

### ISSUE THREAD

**Issue by efJerryYang** [efJerryYang/chatgpt-cli#6]
Error message:
```txt
ModuleNotFoundError: No module named 'readline'   
```
When I try installing it directly with `pip install readline`, another error occurs:
```txt
error: this module is not meant to work on Windows  
```
So, it is clear that Python on Windows just does not support the library `readline`, we may need to use other alternatives for this functionality.

**Comment by PraxTube** [comment]
I tried to replace `readline` with `sys.stdin.readline` but that does not work, because it does not support the line buffer mechanic (so it reads from a blank line instead from the `....`).

Possible alternatives are:
- prompt_toolkit
- curses
- click

I haven't tried any of them, but I am sure that all of them would require at least some level of rework.

**Comment by PraxTube** [comment]
Though I gotta ask, do you use the multiline input method often? I haven't found myself using it a single time (at least now that the `!editor` is there). If I know I need to write a longer message or paste something I will use an editor, and if the message is small enough I can use the in-place variant (often without exceeding one line).

Perhaps the multiline does not need to be supported? Well this is only my opinion anyways. Of course, there is not a lot of harm in supporting it.

**Comment by efJerryYang** [comment]
Yes, it makes sense to remove the previous implementation of supporting reading multiple lines if we already have the `!editor` command. However, as some users (like me :cry: ) have already got very familiar with this usage, it would be much better to deprecate this functionality gradually later rather than do it immediately.

**Comment by efJerryYang** [comment]
I find an alternative for Windows, `pyreadline3`. It works but there is still a display problem with that library. I am trying to figure out the solution and will close this issue after solving it.

**Comment by PraxTube** [comment]
> However, as some users (like me cry ) have already got very familiar with this usage, it would be much better to deprecate this functionality gradually later rather than do it immediately.

Yes that is true haha.

> I find an alternative for Windows, `pyreadline3`.

Ah nice, I only saw `pyreadline` which stopped being supported 8 years ago. But `pyreadline3` seems to be actively maintained.

**Comment by PraxTube** [comment]
Though I am a little confused, it seems like we are still using `readline` in `io.py` in version `0.1.6`. I am using Linux so I can't test the windows version (I also don't have a VM set up atm), but to me this should still generate the same module error.

Or is `pyreadline3` somehow able to correct the built-in `readline`? That would seem pretty magic.

**Comment by efJerryYang** [comment]
Do you mean the `import readline` in the `io.py`? That's correct, once package `pyreadline3` is installed, it would provide support for module `readline`. I test it on a vbox virtual machine Win10 `Microsoft Windows [Version 10.0.19045.2728]`.

You can see the updated dependency in `pyproject.toml`  and `requirements.txt`.

**Comment by PraxTube** [comment]
Yes that's exactly what I mean. I thought you would need to do something like `from pyreadline3 import readline` but this is even better.

**Comment by efJerryYang** [comment]
Yes, I understand your concern. You can see below:

![Screenshot_2023-03-26_133218](https://user-images.githubusercontent.com/76581033/227773099-509a3788-06ed-446a-b2de-49e10de5b8ce.png)

**Comment by PraxTube** [comment]
Looking great!
