### ISSUE TITLE
Use python linter/formatter and CI

### ISSUE THREAD

**Issue by PraxTube** [efJerryYang/chatgpt-cli#7]
I want to propose the usage and implementation of a python linter/formatter (i.e. [black](https://github.com/psf/black)). I think there are only upsides to be had once the initial implementation is complete. It makes the code more consistent and readable.

This would also open the door to use a CI (i.e. Github Actions).

I linted with black on a previous version of the code base and it would only reformat 3 files (with default settings). So the code base is already quite clean and implementing a linter/formatter wouldn't quite a lot of conflicts.

**Comment by efJerryYang** [comment]
Great, thank you for your suggestion. I have never implemented CI before, so I haven't tried it out in this project yet. Feel free to do so.
